service: quotebot

provider:
  name: aws
  runtime: nodejs4.3

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:  
          path: webook
          method: GET
          integration: lambda
      - http: 
          path: webook
          method: POST
          integration: lambda
